- name: Copy Spark archive
  copy: src=../../../packages/spark-{{ spark_version }}.tar.gz dest=/tmp/spark-{{ spark_version }}.tar.gz

- name: Extract archive
  command: chdir=/usr/local /bin/tar xvf /tmp/spark-{{ spark_version }}.tar.gz -C /tmp/ creates=/tmp/spark-{{ spark_version }}

- name: Remove an eventual previous yarn shuffle assembly
  shell: rm -rf /usr/local/hadoop/share/hadoop/yarn/spark-*-yarn-shuffle.jar

- name: Copy yarn shuffle assembly
  shell: cp /tmp/spark-{{ spark_version }}/lib/spark-{{ spark_version }}-yarn-shuffle.jar /usr/local/hadoop/share/hadoop/yarn

- name: Change ownership of the shuffle assembly
  file: path=/usr/local/hadoop/share/hadoop/yarn/spark-{{ spark_version }}-yarn-shuffle.jar owner=hadoop group=hadoop mode="u=rwx,g=rwx,o=rx"

- name: Remove spark archive
  shell: rm -rf /tmp/spark-{{ spark_version }}*

- name: Download jackson-databind jar
  shell: cd /usr/local/hadoop/share/hadoop/yarn; wget http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar; chown hadoop:hadoop jackson-databind-2.2.3.jar

- name: Download jackson-core jar
  shell: cd /usr/local/hadoop/share/hadoop/yarn; wget http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar; chown hadoop:hadoop jackson-core-2.2.3.jar

- name: Download jackson-annotations jar
  shell: cd /usr/local/hadoop/share/hadoop/yarn; wget http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar; chown hadoop:hadoop jackson-annotations-2.2.3.jar

- name: Copy leveldb library
  copy: src=../../../../conf/libleveldbjni.so dest=/usr/local/hadoop/lib/native/libleveldbjni.so group=hadoop
  

  
