- name: create the yarn data dir
  command: mkdir -p {{ yarn_nodemanager_local_dirs }} creates={{ yarn_nodemanager_local_dirs }}

- name: change dirs ownership
  command: chown -R yarn:hadoop {{ yarn_nodemanager_local_dirs }}/..
  
  

  
