---
- hosts: all
  tasks:
  - name: Remove hadoop
    shell: rm -rf /opt/hadoop*
  - shell: rm -f  /usr/local/hadoop
  - shell: rm -rf {{ dfs_namenode_name_dir }}
  - shell: rm -rf {{ dfs_datanode_data_dir }}
  - shell: rm -rf {{ dfs_namenode_checkpoint_dir }}
  - shell: rm -rf {{ yarn_nodemanager_local_dirs }}
  - shell: rm -rf /home/hadoop /home/hdfs /home/yarn /home/mapred
  - shell: userdel hdfs
  - shell: userdel yarn
  - shell: userdel mapred
  - shell: userdel hadoop

- hosts: master
  tasks:
  - name: Remove hadoop
    shell: userdel zookeeper
  - shell: rm -rf /home/zookeeper
  - shell: rm -rf /opt/zookeeper*
  - shell: rm -f  /usr/local/zookeeper

- hosts: master
  name: for each node remove all the generated keytabs
  tasks:
  - shell: kadmin.local -q "delprinc -force hdfs/{{ item }}.{{dns_domain}}@{{ kerberos_realm }}"
    with_items: groups.slaves
    when: secure
  - shell: kadmin.local -q "delprinc -force yarn/{{ item }}.{{dns_domain}}@{{ kerberos_realm }}"
    with_items: groups.slaves
    when: secure
  - shell: kadmin.local -q "delprinc -force HTTP/{{ item }}.{{dns_domain}}@{{ kerberos_realm }}"
    with_items: groups.slaves
    when: secure
  - shell: kadmin.local -q "delprinc -force hdfs/{{ master }}.{{dns_domain}}@{{ kerberos_realm }}"
    when: secure
  - shell: kadmin.local -q "delprinc -force yarn/{{ master }}.{{dns_domain}}@{{ kerberos_realm }}"
    when: secure
  - shell: kadmin.local -q "delprinc -force HTTP/{{ master }}.{{dns_domain}}@{{ kerberos_realm }}"
    when: secure