---
- hosts: master
  tasks:
  - name: Start yarn
    shell: su - yarn -c '/usr/local/hadoop/sbin/start-yarn.sh'
  - shell: su - mapred -c '/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver'